name: Run Python script and merge output

on:
  push:
    branches:
      - main

jobs:
  merge_output:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install necessary packages
      run: |
        pip install pandas openpyxl

    - name: Run Python scripts
      run: |
        python main.py

    - name: Merge outputs and write to Excel
      run: |
        python merge_output.py
      env:
        INPUT_FILE: output1.csv,output2.csv
        OUTPUT_FILE: merged_output.xlsx
